const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Generate property verification report
exports.generateVerificationReport = async (propertyRequest) => {
  try {
    const doc = new PDFDocument();
    const filename = `verification_report_${propertyRequest._id}.pdf`;
    const filepath = path.join('uploads', filename);

    // Pipe PDF to file
    doc.pipe(fs.createWriteStream(filepath));

    // Header
    doc.fontSize(20).text('Gorakhpur Property Check', 50, 50);
    doc.fontSize(16).text('Property Verification Report', 50, 80);
    doc.moveDown();

    // Property Details
    doc.fontSize(14).text('Property Details:', 50, 120);
    doc.fontSize(12)
       .text(`Request ID: #${propertyRequest._id}`, 50, 140)
       .text(`Property Address: ${propertyRequest.propertyAddress}`, 50, 160)
       .text(`Property Type: ${propertyRequest.propertyType}`, 50, 180)
       .text(`Service Type: ${propertyRequest.serviceType}`, 50, 200)
       .text(`Amount: ₹${propertyRequest.amount}`, 50, 220);

    // Customer Details
    doc.fontSize(14).text('Customer Details:', 50, 260);
    doc.fontSize(12)
       .text(`Name: ${propertyRequest.user.name}`, 50, 280)
       .text(`Phone: ${propertyRequest.user.phone}`, 50, 300)
       .text(`Email: ${propertyRequest.user.email || 'N/A'}`, 50, 320);

    // Verification Results (Sample)
    doc.fontSize(14).text('Verification Results:', 50, 360);
    doc.fontSize(12)
       .text('✓ Legal Status: Clear', 50, 380)
       .text('✓ Ownership: Verified', 50, 400)
       .text('✓ Encumbrance: No issues found', 50, 420)
       .text('✓ Survey Settlement: Completed', 50, 440)
       .text('✓ Revenue Records: Updated', 50, 460);

    // Footer
    doc.fontSize(10)
       .text('This report is generated by Gorakhpur Property Check', 50, 700)
       .text('For any queries, contact: +91 9693420595', 50, 715)
       .text(`Generated on: ${new Date().toLocaleDateString()}`, 50, 730);

    doc.end();

    return {
      success: true,
      filename: filename,
      filepath: filepath
    };
  } catch (error) {
    console.error('❌ Report generation failed:', error);
    return {
      success: false,
      error: error.message
    };
  }
};

// Generate Excel report for admin
exports.generateExcelReport = async (requests) => {
  try {
    // This would use a library like xlsx or exceljs
    // For now, returning CSV format
    
    let csvContent = 'Request ID,Customer Name,Phone,Property Address,Service Type,Amount,Status,Date\n';
    
    requests.forEach(request => {
      csvContent += `#${request._id},${request.user.name},${request.user.phone},"${request.propertyAddress}",${request.serviceType},₹${request.amount},${request.status},${request.createdAt.toLocaleDateString()}\n`;
    });

    const filename = `property_requests_${Date.now()}.csv`;
    const filepath = path.join('uploads', filename);
    
    fs.writeFileSync(filepath, csvContent);

    return {
      success: true,
      filename: filename,
      filepath: filepath
    };
  } catch (error) {
    console.error('❌ Excel report generation failed:', error);
    return {
      success: false,
      error: error.message
    };
  }
};